### PR TITLE
Flutter_flags: Bug fixing

### PR DESCRIPTION
**Pull request by ByJerome**
- #70 removed almost all clipPath-tags inside the defs-tag (Flags were cut off)
- #77 #71  changed the pt values to pixel (1pt ~= 1.3333333px)
- #69 #74 #67 Flutter svg goes through the ids from top to bottom. In some svg's there is first a href="url(#a)" link to an id 
   which is set afterwards with id="a". I added the required svg elements to the defs tag for the flags where the error occurred. I 
   did NOTHING to the flags themselves except the Korean flag because it was broken.
- Added around 60 missing flags into the FlagsCode Enum
- Updated flutter_svg to version 1.0.3
- Updated the flags (6.6.3) provided by https://github.com/lipis/flag-icons

All flags are working without any errors either on 4x3 or 1x1 format. & nearly all issues are resolved with this pr.

This is the first pull request I have ever made. Be kind with me 😄

### CODE REVIEW

**Comment by JulianBissekkou** [comment]
Nice! @LunaGao Can you give this a review?

**Comment by daniel-hopkins** [comment]
I see this merge, but the version on pub.dev has not been updated.
Is that correct?

**Comment by mahanabd** [comment]
why the library not update flutter_svg?

**Comment by stefanschaller** [comment]
Any information why flutter_svg are not up to date?

**Comment by LunaGao** [comment]
Updated.

**Pull request merged**
